### ISSUE TITLE
closes as soon as it's opened

### ISSUE THREAD

**Issue by Mirjuuu** [OSintt/discord-token-bruteforce#1]
Am I missing something? What stuff do I need for it to work?

**Comment by OSintt** [comment]
have you installed its requirements?

**Comment by Mirjuuu** [comment]
I’m sorry but I’m not too sure what I need, I’m like VERY new to Python. Out of curiosity though how long does this one take to work? As I have a different code running right now and I’m not sure if it’s worth replacing it with yours to save time (it’s been around 10 hours)

**Comment by OSintt** [comment]
Just use pip install in console and install the following:

tkinter
colorama
urllib
requests
base64

The duration of a bruteforce process is quite random, so I wouldn't know how to answer you. However, this program is efficient enough in its speed of sending requests to the discord api
