### ISSUE TITLE
Says i need a password

### ISSUE THREAD

**Issue by DaveyBoigames** [OSintt/discord-token-bruteforce#2]
What is the password that it's asking for?

**Comment by ian4u** [comment]
Its 123
Proof:
https://cdn.discordapp.com/attachments/1103728329569349676/1111759064309960834/image.png

**Comment by TW-Knrl** [comment]
first of all the password is 123, but instead of making an "issue" without a reason u couldve js read the code, i guess u would run an open source virus without knowing.

**Comment by ian4u** [comment]
Lmao
