### ISSUE TITLE
says ID invalid

### ISSUE THREAD

**Issue by Plusxryy** [OSintt/discord-token-bruteforce#3]
when entering the ID to do the bruteforce it says it is invalid
![image](https://github.com/OSintt/discord-token-bruteforce/assets/69547476/bc07157f-18bf-4717-af09-cc6117fc2e08)

**Comment by OSintt** [comment]
maybe cuz id u r entering is invalid idk

**Comment by Suxirda** [comment]
Same issue, When i copy paste the ID it says "ID inválida, inténtelo de nuevo"... What to do?

**Comment by MarcusM2092** [comment]
change it to 19 characters here "if (id.isdigit() and len(id) == <19>):"

**Comment by OSintt** [comment]
fixed
