### ISSUE TITLE
how to install and use

### ISSUE THREAD

**Issue by CLANCyGILROY-png** [OSintt/discord-token-bruteforce#6]
im not an expert on these things and i'd like an explanaition on it please.

**Comment by OSintt** [comment]
git clone https://github.com/OSintt/discord-token-bruteforce
pip install -r requirements.txt 
cd discord-token-bruteforce && python tokenbf.py

:)

**Comment by CLANCyGILROY-png** [comment]
im sorry for asking again but i dont understand a thing i have never used these things nor phyton so its hard for me sorry again

**Comment by CLANCyGILROY-png** [comment]
fixed that one issue but i enter the id at the end the thing crashes, and gives inf errors for random bruteforce why?

**Comment by CLANCyGILROY-png** [comment]
ok now the id works but gives me this errors
![Uploading Screenshot 2024-07-14 140622.png…]()

**Comment by CLANCyGILROY-png** [comment]
what is this

![Screenshot 2024-07-14 140622](https://github.com/user-attachments/assets/88247c4a-9fdd-4dda-bafb-1a0de94624ff)
